### ISSUE TITLE
BuilderSonic improvements [development_fixes103]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_builders#37]
```python
    @builder_method()
    def build(self, reset=False):
        """
        kosmos  'j.builders.apps.sonic.build()'
        :param reset:
        :return:
        """
        j.builders.runtimes.rust.install(reset=reset)

        if not j.core.platformtype.myplatform.platform_is_osx:
            self.system.package.install("clang")
        self.profile.env_set_part("PATH", j.builders.runtimes.rust.DIR_CARGOBIN)
        self._execute("rustup update")
        self._remove("/sandbox/bin/sonic")
        self._execute("cargo install sonic-server --force", timeout=3600 * 2, retry=2)

    @builder_method()
    def install(self, reset=False):
        """
        kosmos  'j.builders.apps.sonic.install()'
        :param reset:
        :return:
        """
        self._execute("cp %s/sonic /sandbox/bin/" % j.builders.runtimes.rust.DIR_CARGOBIN)
```
- if the binary exists in `/sandbox/bin/` it should do nothing unless reset is True
- rust installation shouldn't be required unless reset is True
the current implementation defeats the purpose of shipping sonic binary and makes the first time to start threebot super slow because of building sonic, rocksdb.. etc

**Comment by abom** [comment]
In another branch, i'd an error which exposes where sonic builder is called.
 
```
127.0.0.1 - - [2019-11-17 19:03:06] "GET /wiki/chat HTTP/1.1" 200 3202 0.019190                                                           [147/11666]
system__system                                                                                                                                       
system__system                                                                                                                                       
Traceback (most recent call last):                                                                                                                   
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 862, in _handle                                                                      
    return route.call(**args)                                                                                                                        
  File "/usr/local/lib/python3.6/dist-packages/bottle.py", line 1742, in wrapper                                                                     
    rv = callback(*a, **ka)                                                                                                                          
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/wiki/BottleWebServerWiki.py", line 29, in _enable_cors                                      
    return fn(*args, **kwargs)                                                                                                                       
  File "/sandbox/lib/jumpscale/threebot_packages/zerobot/wiki/BottleWebServerWiki.py", line 132, in docsite_handler                                  
    content = j.sal.bcdbfs.file_read(full_path)                                                                                                      
  File "/sandbox/lib/jumpscale/Jumpscale/sal/bcdbfs/BCDBFS.py", line 289, in file_read                                                               
    return self._file_model.file_read(path)                                                                                                          
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/models_threebot/FILE.py", line 154, in file_read                                                  
    file = self.get_by_name(name=path)                                                                                                               
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 300, in get_by_name                                                           
    list_obj = self.find(nid=nid, **args)                                                                                                            
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 629, in find                                                                  
    for id in self.find_ids(nid=nid, **kwargs):                                                                                                      
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 602, in find_ids                                                              
    cursor = self._find_query(nid, **kwargs)                                                                                                         
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 584, in _find_query                                                           
    return self.query_model([field], whereclause, values)                                                                                            
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 588, in query_model                                                           
    query = f"select {fieldstring} FROM {self.index.sql_table_name} "                                                                                
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModel.py", line 98, in index                                                                  
    self._index_ = indexklass(model=self, reset=False)                                                                                               
  File "/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py", line 63, in __init__
    self._init(**kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModelIndex.py", line 64, in _init
    self.sonic  # sonic needs to be started and needs to exist !
  File "/sandbox/lib/jumpscale/Jumpscale/data/bcdb/BCDBModelIndex.py", line 147, in sonic
    self._sonic = j.clients.sonic.get_client_bcdb()
  File "/sandbox/lib/jumpscale/Jumpscale/clients/sonic/SonicFactory.py", line 21, in get_client_bcdb
    j.builders.apps.sonic.install()
AttributeError: 'Jumpscale' object has no attribute 'builders'
```

**Comment by serboctor** [comment]
Fixed here on branch `development_fixes_103` https://github.com/threefoldtech/jumpscaleX_builders/commit/227ae0fc2650cd862cb28ac99dadf1b05920bbe9

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
